from . import cluster
from .nop import Nop
from .accCore import *
from .taskdag import TaskDAG, CONVTaskNode, LRLTaskNode, GemmTaskNode, DPConvTaskNode
from .schedule import Schedule
from .bufmanage import bufManager
from .util import manhattan_distance, idx2coreidx, coreidx2idx, find_center_coreidx
import math
from tabulate import tabulate
from .statistic import Statistic

class Evaluator:
    def __init__(self, nn_name, taskDag: TaskDAG, map_order: list, nop: Nop, cluster: Cluster, core_mask:np.array ,monitor:Statistic, verbose=False):
        '''
        evaluate can caculate the energy cost and latency with the given task DAG, map order and hardware
        :param taskDag: task Dag generated in taskDag.py
        :param map_order: mapping order generated by scheduler
        :param nop: network on package including DRAM list
        :para core_mask: the allcated core mask for the workload nn_name
        :param cluster: hardware info
        '''
        self.nn_name = nn_name
        self.core_mask = core_mask
        self.numCore = np.sum(core_mask)
        self.nop = nop
        self.taskDag = taskDag
        self.map_order = map_order
        self.cluster = cluster
        self.dram_manager = bufManager(4096 * 1024 * 1024)
        self.ubuf_managers = [bufManager(cluster.get_buf_size('ubuf')) for i in range(self.numCore)]
        self.order_latency = []
        self.buf_cost_dict = {}
        self.order_nop_cost = []
        self.order_noc_cost = []
        self.order_dram_cost = []
        self.order_comp_cost = []
        self.bottleneck = []
        self.monitor = monitor
        self.verbose = False
        for buf_name in self.cluster.core_mem.memory.keys():
            self.buf_cost_dict[buf_name] = []
        self.idx2coreidx_map = []   ## since the idx2coreidx is exhaustive method, do it only at init and cache them, 
                                    ## coreidx2idx -> self.idx2coreidx_map.index(coreidx), idx2coreidx -> self.idx2coreidx_map[idx]
        for i in range(self.numCore):
            self.idx2coreidx_map.append(idx2coreidx(i,self.core_mask))

    def evaluate(self):
        task_cur_list = ['NA' for i in range(self.numCore)]
        for order, tasks in enumerate(self.map_order):
            cyc_nop_in, cost_noc_in, cost_nop_in, cost_dram_in = self.evalute_input_data_access(tasks, task_cur_list, order)
            cyc_core, cost_comp = self.evaluate_computation(tasks)
            # print(f'compute: {cyc_core}')
            cyc_nop_out, cost_noc_out, cost_nop_out, cost_dram_out = self.evaluate_output_data_access(order, tasks,
                                                                                        self.ubuf_managers)
            for buf_name in self.buf_cost_dict.keys():
                energy = self.cluster.get_buf_cost(buf_name)
                self.buf_cost_dict[buf_name].append(energy)
            cyc_list = [cyc_core, cyc_nop_out,]
            latency = cyc_nop_in + max(cyc_list)
            # print(f'order:{order}, latency:{latency}, delay in:{cyc_nop_in}, delay core:{cyc_core}, delay out:{cyc_nop_out}')
            cost_noc = cost_noc_in + cost_noc_out
            cost_nop = cost_nop_in + cost_nop_out
            cost_DRAM = cost_dram_in + cost_dram_out
            self.bottleneck.append(cyc_list.index(max(cyc_list)))
            self.order_latency.append(latency)
            self.order_noc_cost.append(cost_noc)
            self.order_nop_cost.append(cost_nop)
            self.order_dram_cost.append(cost_DRAM)
            self.order_comp_cost.append(cost_comp)
            self.monitor.update_external_info(self.nn_name, order, latency, cost_noc, cost_nop, cost_DRAM)
            core_info = self.cluster.gen_core_info()
            core_cyc = self.cluster.cycle.copy()
            core_utl = np.array(core_cyc) / latency
            mtxu_utl = self.cluster.mtxu_utl.copy()
            self.monitor.update_internal_info(self.nn_name, order, core_info, core_utl)
            # self.monitor.update_mtxu_grid_utl(self.nn_name, order, mtxu_utl)
            self.cluster.clear()
            task_cur_list = tasks
            # print(f'{order}: {tasks}, communication cost: {cost_noc+cost_nop}')

    def evalute_input_data_access(self, task_mapping_list, task_cur_list, cur_order):
        self.nop.clear()
        ifm_data_cat, wei_data_cat = self.classifiy_input_data(task_mapping_list)  # classificate the same ifm and wei data
        task_ifm_rest = dict()
        task_wei_rest = dict()
        for task_name in task_mapping_list:
            if task_name == 'NA': continue
            ifm_vol = self.taskDag.get_ifm_volume(task_name)
            wei_vol = self.taskDag.get_wei_volume(task_name)
            task_ifm_rest[task_name] = ifm_vol
            task_wei_rest[task_name] = wei_vol
        # IFM data movement
        for ifm_data_tasks in ifm_data_cat:
            if len(ifm_data_tasks) > 0:
                coreidx_list = []
                for ifm_data_name in ifm_data_tasks:
                    idx = task_mapping_list.index(ifm_data_name)
                    # coreidx_list.append(idx2coreidx(idx, self.core_mask))
                    coreidx_list.append(self.idx2coreidx_map[idx])
                map_center_idx = find_center_coreidx(coreidx_list)
                map_name = ifm_data_tasks[0]
                ifm_volume = self.taskDag.get_ifm_volume(map_name)
                ifm_intra_reuse_idx, _ = self.check_intra_data_reuse(task_cur_list, map_name)
                if True in ifm_intra_reuse_idx:  # exist IFM data sharing in intra-layer level
                    ifm_src_tmp = self.find_intra_data_src(ifm_intra_reuse_idx, map_center_idx)
                    # ifm_src_cidx = idx2coreidx(ifm_src_tmp, self.core_mask)
                    ifm_src_cidx = self.idx2coreidx_map[ifm_src_tmp]
                    self.cluster.buf_read(ifm_src_cidx, 'ubuf', ifm_volume)
                    dst_cidx_list = []
                    for ifm_data_name in ifm_data_tasks:
                        idx = task_mapping_list.index(ifm_data_name)
                        task_ifm_rest[ifm_data_name] -= ifm_volume
                        # dst_cidx = idx2coreidx(idx, self.core_mask)
                        dst_cidx = self.idx2coreidx_map[idx]
                        dst_cidx_list.append(dst_cidx)
                        if not ifm_intra_reuse_idx[idx]:  ## if true, the intra IFM reuse in same core, don't need move
                            self.cluster.buf_write(dst_cidx, 'ubuf', ifm_volume)
                    self.nop.move_between_core(ifm_src_cidx, dst_cidx_list, ifm_volume)
                else:  # check the inter layer reuse in on-chip ubuf
                    for i, ubuf in enumerate(self.ubuf_managers):
                        stored_list = ubuf.get_stored_list()
                        reused_ofm_tmp = 0
                        for stored_ofm_name in stored_list:
                            reused_ofm_tmp += self.taskDag.get_inter_layer_reuse(stored_ofm_name, map_name)
                        if reused_ofm_tmp > 0:
                            # src_cidx = idx2coreidx(i, self.core_mask)
                            src_cidx = self.idx2coreidx_map[i]
                            dst_cidx_list = []
                            for ifm_data_name in ifm_data_tasks:
                                idx = task_mapping_list.index(ifm_data_name)
                                # dst_cidx = idx2coreidx(idx, self.core_mask)
                                dst_cidx = self.idx2coreidx_map[idx]
                                dst_cidx_list.append(dst_cidx)
                                task_ifm_rest[ifm_data_name] -= reused_ofm_tmp
                                if i != idx:    # if src_core == dst_core, don't need move
                                    self.cluster.buf_write(dst_cidx, 'ubuf', reused_ofm_tmp)
                            if not (len(dst_cidx_list) == 1 and src_cidx[0] == dst_cidx_list[0][0]
                                    and src_cidx[1] == dst_cidx_list[0][1]):
                                # when dst only 1 core, and src and dst is same, don't need move
                                self.cluster.buf_read(src_cidx, 'ubuf', reused_ofm_tmp)
                            self.nop.move_between_core(src_cidx, dst_cidx_list, reused_ofm_tmp)
        # WEI data movement
        for wei_data in wei_data_cat:
            if len(wei_data) > 0:
                coreidx_list = []
                for wei_data_name in wei_data:
                    idx = task_mapping_list.index(wei_data_name)
                    # coreidx_list.append(idx2coreidx(idx, self.core_mask))
                    coreidx_list.append(self.idx2coreidx_map[idx])
                map_center_idx = find_center_coreidx(coreidx_list)
                map_name = wei_data[0]
                wei_volume = self.taskDag.get_wei_volume(map_name)
                _, wei_intra_reuse_idx = self.check_intra_data_reuse(task_cur_list, map_name)
                if True in wei_intra_reuse_idx and wei_volume > 0:  # exist WEI data sharing in intra-layer level
                    wei_src_tmp = self.find_intra_data_src(wei_intra_reuse_idx, map_center_idx)
                    # src_cidx = idx2coreidx(wei_src_tmp, self.core_mask)
                    src_cidx = self.idx2coreidx_map[wei_src_tmp]
                    dst_cidx_list = []
                    self.cluster.buf_read(src_cidx, 'ubuf', wei_volume)
                    for wei_data_name in wei_data:
                        idx = task_mapping_list.index(wei_data_name)
                        # dst_cidx = idx2coreidx(idx, self.core_mask)
                        dst_cidx = self.idx2coreidx_map[idx]
                        dst_cidx_list.append(dst_cidx)
                        task_wei_rest[wei_data_name] -= wei_volume
                        if not wei_intra_reuse_idx[idx]:  ## if true, wei data in same core, don't need move
                            self.cluster.buf_write(dst_cidx, 'ubuf', wei_volume)
                            # self.cluster.buf_read(src_cidx, 'ubuf', wei_volume)
                    self.nop.move_between_core(src_cidx, dst_cidx_list, wei_volume)
                # For GemmTaskNode, the weight data is also stored in ubuf
                elif isinstance(self.taskDag[map_name], GemmTaskNode):
                    for i, ubuf in enumerate(self.ubuf_managers):
                        stored_list = ubuf.get_stored_list()
                        reused_wei_tmp = 0
                        for stored_ofm_name in stored_list:
                            reused_wei_tmp += self.taskDag.get_inter_layer_reuse(stored_ofm_name, map_name)
                        if reused_wei_tmp > 0:
                            # src_cidx = idx2coreidx(i, self.core_mask)
                            src_cidx = self.idx2coreidx_map[i]
                            dst_cidx_list = []
                            for wei_data_name in wei_data:
                                idx = task_mapping_list.index(wei_data_name)
                                # dst_cidx = idx2coreidx(idx, self.core_mask)
                                dst_cidx = self.idx2coreidx_map[idx]
                                dst_cidx_list.append(dst_cidx)
                                task_wei_rest[wei_data_name] -= reused_wei_tmp
                                if i != idx:    # if src_core == dst_core, don't need move
                                    self.cluster.buf_write(dst_cidx, 'ubuf', reused_wei_tmp)
                            if not (len(dst_cidx_list) == 1 and src_cidx[0] == dst_cidx_list[0][0]
                                    and src_cidx[1] == dst_cidx_list[0][1]):
                                # when dst only 1 core, and src and dst is same, don't need move
                                self.cluster.buf_read(src_cidx, 'ubuf', reused_wei_tmp)
                            self.nop.move_between_core(src_cidx, dst_cidx_list, reused_wei_tmp)

        # the rest data will read from DRAM
        for ifm_data_tasks in ifm_data_cat:
            if len(ifm_data_tasks) > 0:
                rest_vol = task_ifm_rest[ifm_data_tasks[0]]
                if rest_vol > 0:
                    dst_cidx_list = []
                    for ifm_data_name in ifm_data_tasks:
                        idx = task_mapping_list.index(ifm_data_name)
                        dst_cidx = idx2coreidx(idx, self.core_mask)
                        dst_cidx_list.append(dst_cidx)
                        rest_vol_tmp = task_ifm_rest[ifm_data_name]
                        assert rest_vol == rest_vol_tmp, f'Task classification error, {ifm_data_cat}'  ## the same IFM, hence the rest data is also same
                        self.cluster.buf_write(dst_cidx, 'ubuf', rest_vol)
                    self.nop.read_from_DRAM(dst_cidx_list, rest_vol)
        for wei_data_tasks in wei_data_cat:
            if len(wei_data_tasks) > 0:
                rest_vol = task_wei_rest[wei_data_tasks[0]]
                if rest_vol > 0:
                    dst_cidx_list = []
                    for wei_data_name in wei_data_tasks:
                        idx = task_mapping_list.index(wei_data_name)
                        dst_cidx = idx2coreidx(idx, self.core_mask)
                        dst_cidx_list.append(dst_cidx)
                        rest_vol_tmp = task_wei_rest[wei_data_name]
                        assert rest_vol == rest_vol_tmp
                        self.cluster.buf_write(dst_cidx, 'ubuf', rest_vol)
                    self.nop.read_from_DRAM(dst_cidx_list, rest_vol)
        latency = self.nop.get_time()
        noc_cost = self.nop.get_noc_cost()
        nop_cost = self.nop.get_nop_cost()
        dram_cost = self.nop.get_dram_cost()
        return latency, noc_cost, nop_cost, dram_cost

    def evaluate_computation(self, task_mapping_list):
        for idx, task_name in enumerate(task_mapping_list):
            if task_name == 'NA': continue
            task_node = self.taskDag[task_name]
            l0a_read_size = l0a_write_size = l0b_read_size = l0b_write_size = l0c_read_size = l0c_write_size = 0
            l1c_read_size = l1c_write_size = ubuf_read_size = ubuf_write_size = 0
            # cidx = idx2coreidx(idx, (self.cluster.xlen, self.cluster.ylen))
            cidx = self.idx2coreidx_map[idx]
            ifm_volume = task_node.fromVolume()
            ofm_volume = task_node.toVolume()
            wei_volume = task_node.total_filter_size()
            bo, ho, wo, co = task_node.get_ofm_shape()
            ci = task_node.fromrange.cRange.length()
            
            if isinstance(task_node, CONVTaskNode) or isinstance(task_node, GemmTaskNode):
                hfil, wfil = task_node.hfil, task_node.wfil
                padding_rate = task_node.get_padding_rate()
                mac_tot_ops = task_node.total_ops()
                ci = 1 if isinstance(task_node, DPConvTaskNode) else ci
                (hw_utl, co_ult, cin_utl) = self.cluster.cal_mtxu_utl([ho,wo,ci,co])
                # along cout dim, how many times that ifm should be read
                co_loop_ideal = co / self.cluster.w_pe
                co_loop_real = math.ceil(co / self.cluster.w_pe)
                cin_loop_ideal = (ci / self.cluster.h_pe)
                cin_loop_real = math.ceil(ci / self.cluster.h_pe)
                # cin_utl = cin_loop_ideal / cin_loop_real
                
                comp_cyc = math.ceil(mac_tot_ops / co_ult / hw_utl / cin_utl / self.cluster.w_pe / self.cluster.h_pe)
                l0a_read_size += mac_tot_ops * (1 - padding_rate) / self.cluster.w_pe
                l0b_read_size += mac_tot_ops /  self.cluster.h_pe
                # aloop = math.ceil(ifm_volume / self.cluster.get_buf_size('l0a'))
                # bloop = math.ceil(wei_volume / self.cluster.get_buf_size('l0b'))
                # if ifm_volume * bloop > wei_volume * aloop:  # fix ifm and move wei
                #     l0a_write_size += ifm_volume
                #     l0b_write_size += wei_volume * aloop
                # else:
                #     l0a_write_size += ifm_volume * bloop
                #     l0b_write_size += wei_volume
                ifm_vol_perMM = int(self.cluster.h_pe * ci * hfil * wfil / task_node.ifm_hw_overlap())
                wei_vol_perMM = int(self.cluster.w_pe * ci * hfil * wfil)
                psum_max_perRF = self.cluster.get_buf_size('l0c') // self.cluster.w_pe // self.cluster.get_buf_bw('l0c')
                l0a_fetch_time_perMM = ifm_vol_perMM / self.cluster.get_buf_size('l0a')
                l0b_fetch_time_perMM = wei_vol_perMM / self.cluster.get_buf_size('l0b')
                l0a_fetch_time_hw = ho * wo / self.cluster.h_pe
                l0b_fetch_time_co = co / self.cluster.w_pe
                l0a_fetch_time_tot = l0a_fetch_time_perMM * l0a_fetch_time_hw
                l0b_fetch_time_tot = l0b_fetch_time_perMM * l0b_fetch_time_co
                if l0a_fetch_time_tot <=1 or l0b_fetch_time_tot <= 1:
                    ## l0a or l0b can store all ifm/wei at one time
                    l0a_write_size += ifm_volume
                    l0b_write_size += wei_volume
                    l0c_write_size += ofm_volume
                elif l0a_fetch_time_perMM <= 1 or l0b_fetch_time_perMM <= 1:
                    ## l0a or l0b can store >1 data volum of perMM
                    aloop = math.ceil(ifm_volume / self.cluster.get_buf_size('l0a'))
                    bloop = math.ceil(wei_volume / self.cluster.get_buf_size('l0b'))
                    l0c_write_size += ofm_volume
                    if ifm_volume * bloop  > wei_volume * aloop:  # fix ifm and move wei
                        l0a_write_size += ifm_volume
                        l0b_write_size += wei_volume * bloop
                    else:
                        l0a_write_size += ifm_volume * aloop
                        l0b_write_size += wei_volume
                else:
                    ## l0a or l0b can't store the data of per MM, 
                    ## can't fix WEI/IFM in l0 buffer, hence l0a, l0b need read data from ubuf multiple times 
                    l0a_fetch_time_perMM = math.ceil(l0a_fetch_time_perMM)
                    l0b_fetch_time_perMM = math.ceil(l0b_fetch_time_perMM)
                    l0a_loop_times = math.ceil(l0b_fetch_time_co)
                    l0b_loop_times = math.ceil(l0a_fetch_time_hw)
                    ## considering the l0c can store the partial sum, hence the ifm/wei can be fixed psum_max_perRF times
                    if l0a_loop_times * ifm_volume > l0b_loop_times * wei_volume:
                        l0c_psum_reuse = min(l0a_loop_times, psum_max_perRF)
                        l0a_loop_times = math.ceil(l0a_loop_times / l0c_psum_reuse)
                    else:
                        l0c_psum_reuse = min(l0b_loop_times, psum_max_perRF)
                        l0b_loop_times = math.ceil(l0b_loop_times / l0c_psum_reuse)
                    l0a_write_size += ifm_volume * l0a_loop_times
                    l0b_write_size += wei_volume * l0b_loop_times
                    l0c_write_size += ofm_volume * l0c_psum_reuse  
                                              
                ubuf_read_size += l0a_write_size + l0b_write_size
                ubuf_read_cyc = math.ceil((ubuf_read_size) / self.cluster.get_buf_bw('ubuf'))
                l0c_write_size += mac_tot_ops / (self.cluster.h_pe * cin_utl)
                l0c_read_size += mac_tot_ops  / (self.cluster.h_pe * cin_utl)
                l1c_read_size += ofm_volume
                l1c_write_size += ofm_volume
                ubuf_write_size += ofm_volume
                self.cluster.set_mtxu_utl(cidx, [co_loop_ideal, co_loop_real, cin_loop_ideal, cin_loop_real, hw_utl])
                self.cluster.mtxu_ops_add(cidx, mac_tot_ops )
                self.cluster.set_cycle(cidx, max(comp_cyc, ubuf_read_cyc))
            elif isinstance(task_node, LRLTaskNode):
                ifm_volume = task_node.fromVolume()
                ofm_volume = task_node.toVolume()
                vecu_tot_ops = task_node.total_ops()
                ubuf_read_size += ifm_volume
                ubuf_write_size += ofm_volume
                comp_cyc = math.ceil(vecu_tot_ops / self.cluster.svecu)
                self.cluster.set_cycle(cidx, comp_cyc)
                self.cluster.vecu_ops_add(cidx, vecu_tot_ops)
            else:
                raise TypeError('Task node type not supported')
            # self.cluster.set_cycle(cidx, comp_cyc)
            self.cluster.buf_read(cidx, 'ubuf', ubuf_read_size)
            self.cluster.buf_write(cidx, 'ubuf', ubuf_write_size)
            self.cluster.buf_read(cidx, 'l0a', l0a_read_size)
            self.cluster.buf_write(cidx, 'l0a', l0a_write_size)
            self.cluster.buf_read(cidx, 'l0b', l0b_read_size)
            self.cluster.buf_write(cidx, 'l0b', l0b_write_size)
            self.cluster.buf_read(cidx, 'l0c', l0c_read_size)
            self.cluster.buf_write(cidx, 'l0c', l0c_write_size)
            self.cluster.buf_read(cidx, 'l1c', l1c_read_size)
            self.cluster.buf_write(cidx, 'l1c', l1c_write_size)
        return self.cluster.get_tot_cycle(), self.cluster.get_mtxu_cost() + self.cluster.get_vecu_cost()

    def evaluate_output_data_access(self, cur_order, task_mapping_list, buf_manage_list):
        # ofm writeback and and ubuf update
        self.nop.clear()
        for idx, task_name in enumerate(task_mapping_list):
            buf_manage = buf_manage_list[idx]
            if task_name == 'NA':
                ifm_volume = wei_volume = ofm_volume = 0
                ofm_wb_imm = True
            else:
                task_node = self.taskDag[task_name]
                ifm_volume = task_node.fromVolume()
                wei_volume = task_node.total_filter_size()
                ofm_volume = task_node.toVolume()
                ofm_exe_order = self.taskDag.get_task_exe_time(task_name)
                ofm_wb_order = self.taskDag.get_task_writeback_time(task_name)
                ofm_wb_imm = (ofm_exe_order == ofm_wb_order)
            stored_ofm_names = buf_manage.get_stored_list()

            wb_volume = ofm_volume if ofm_wb_imm else 0
            for stored_ofm_name in stored_ofm_names:
                wb_order = self.taskDag.get_task_writeback_time(stored_ofm_name)
                vld_order = self.taskDag.get_task_valid_time(stored_ofm_name)
                exe_order = self.taskDag.get_task_exe_time(stored_ofm_name)
                if exe_order > cur_order:
                    raise ValueError(
                        f'For {task_name} mapped on core {idx}, OFM is bufferred before generated. Pleas check the '
                        f'mapping and buffering stages.')
                if vld_order <= cur_order:
                    buf_manage.delete_data(stored_ofm_name)
                if wb_order is not None and wb_order <= cur_order:
                    wb_volume += self.taskDag[stored_ofm_name].toVolume()
                    buf_manage.delete_data(stored_ofm_name)
            ## The last step, store ofm data
            if ofm_volume > 0 and ofm_wb_imm == False:
                buf_manage.store_data(task_name, ofm_volume)
            wb_volume += ofm_volume
            cidx = self.idx2coreidx_map[idx]
            self.nop.write_to_DRAM(cidx, wb_volume)
            self.cluster.buf_read(cidx, 'ubuf', wb_volume)
            if buf_manage.free_space() < ifm_volume + wei_volume : ## no ofm, since ofm is in ubuf
                raise ValueError(f'For {task_name} mapped on core {idx}, the ubuf is overflowed. Pleas check the '
                                 f'mapping and buffering stages.')
        latency = self.nop.get_time()
        noc_cost = self.nop.get_noc_cost()
        nop_cost = self.nop.get_nop_cost()
        dram_cost = self.nop.get_dram_cost()
        return latency, noc_cost, nop_cost, dram_cost

    def classifiy_input_data(self, name_list):
        ifm_data = [[] for i in range(self.cluster.xlen * self.cluster.ylen)]
        wei_data = [[] for i in range(self.cluster.xlen * self.cluster.ylen)]
        empty_idx_ifm = 0
        empty_idx_wei = 0
        for name in name_list:
            if name == 'NA': continue
            task_node = self.taskDag[name]
            if not (isinstance(task_node,CONVTaskNode) or isinstance(task_node, GemmTaskNode)):
                ifm_data[empty_idx_ifm].append(name)
                empty_idx_ifm += 1
                continue
            name_tmp = name.split('.')
            layer_name = name_tmp[0]
            b_split = name_tmp[1]
            h_split = name_tmp[2]
            w_split = name_tmp[3]
            c_split = name_tmp[4] 
            isfound_ifm = False
            isfound_wei = False

            for i in range(len(ifm_data)):
                if len(ifm_data[i]) == 0:
                    continue
                else:
                    name_tmp1 = ifm_data[i][0].split('.')
                    layer_name1 = name_tmp1[0]
                    b_split1 = name_tmp1[1]
                    h_split1 = name_tmp1[2]
                    w_split1 = name_tmp1[3]
                    c_split1 = name_tmp1[4]
                    if len(name_tmp) > 5 and len(name_tmp1) > 5:  ## both layer are the group conv layer
                        g_split = name_tmp[-1]
                        g_split1 = name_tmp1[-1]
                        if layer_name == layer_name1 and b_split == b_split1 and h_split == h_split1 and w_split == w_split1 and g_split == g_split1:
                            assert c_split != c_split1
                            ifm_data[i].append(name)
                            isfound_ifm = True
                    elif layer_name == layer_name1 and b_split == b_split1 and h_split == h_split1 and w_split == w_split1:
                        # assert c_split != c_split1
                        if isinstance(task_node, DPConvTaskNode):
                            if c_split == c_split1:
                                ifm_data[i].append(name)
                                isfound_ifm = True
                        else:
                            assert c_split != c_split1
                            ifm_data[i].append(name)
                            isfound_ifm = True
            if not isfound_ifm:
                ifm_data[empty_idx_ifm].append(name)
                empty_idx_ifm += 1

            for i in range(len(wei_data)):
                if len(wei_data[i]) == 0:
                    continue
                else:
                    name_tmp1 = wei_data[i][0].split('.')
                    layer_name1 = name_tmp1[0]
                    b_split1 = name_tmp1[1]
                    h_split1 = name_tmp1[2]
                    w_split1 = name_tmp1[3]
                    c_split1 = name_tmp1[4]
                    if len(name_tmp) > 5 and len(name_tmp1) > 5:  ## both layer are the group conv layer
                        g_split = name_tmp[-1]
                        g_split1 = name_tmp1[-1]
                        if layer_name == layer_name1 and c_split == c_split1 and g_split == g_split1:
                            assert h_split != h_split1 or w_split != w_split1 or b_split != b_split1
                            wei_data[i].append(name)
                            isfound_wei = True
                    elif layer_name == layer_name1 and c_split == c_split1:
                        # print(name_tmp, name_tmp1)
                        assert h_split != h_split1 or w_split != w_split1 or b_split != b_split1
                        wei_data[i].append(name)
                        isfound_wei = True
            if not isfound_wei:
                wei_data[empty_idx_wei].append(name)
                empty_idx_wei += 1

        return ifm_data, wei_data

    def check_intra_data_reuse(self, tasks_name_cur, task_name):
        ## we can use the name to judge whether there is a data reuse
        ifm_reuse = []  ## if if_reuse[0] = true -> the data in core 0, can be reuse by the new task
        wei_reuse = []
        name_list = task_name.split('.')
        layer_name = name_list[0]
        b_split = name_list[1]
        h_split = name_list[2]
        w_split = name_list[3]
        c_split = name_list[4]

        for task_name_cur in tasks_name_cur:
            if task_name_cur == 'NA':
                ifm_reuse_tmp = False
                wei_reuse_tmp = False
            else:
                if task_name_cur == task_name:
                    raise ValueError(f'The tasks are repeat')
                name_cur_list = task_name_cur.split('.')
                ifm_reuse_tmp = (layer_name == name_cur_list[0]) and (b_split == name_cur_list[1]) and (h_split == name_cur_list[2]) and (
                        w_split == name_cur_list[3])
                wei_reuse_tmp = (layer_name == name_cur_list[0]) and (c_split == name_cur_list[4])
            ifm_reuse.append(ifm_reuse_tmp)
            wei_reuse.append(wei_reuse_tmp)
        return ifm_reuse, wei_reuse

    def find_intra_data_src(self, reuse_list, map_cidx):
        '''
        this function can find the shortest source when there are more than 2 ifm/WEI data can be reuse by a new task
        :param ifm_reuse:
        :param map_cidx: 2d core idx
        :return:
        '''
        path_len = len(reuse_list)
        src_idx = 0
        for idx, is_reuse in enumerate(reuse_list):
            if is_reuse:
                # cidx = idx2coreidx(idx, (self.cluster.xlen, self.cluster.ylen))
                cidx = self.idx2coreidx_map[idx]
                dist = manhattan_distance(map_cidx, cidx)
                if dist < path_len:
                    path_len = dist
                    src_idx = idx
        return src_idx

    def clear(self):
        self.dram_manager.clear()
        self.ubuf_managers.clear()
        self.order_latency.clear()
        self.buf_cost_dict.clear()
        self.order_nop_cost.clear()
        self.order_noc_cost.clear()
        self.order_dram_cost.clear()
        self.order_comp_cost.clear()
        self.bottleneck.clear()
        self.idx2coreidx_map.clear()
        self.monitor.clear()
        
    
    def __str__(self):
        header = ['order', 'latency', 'noc (pJ)', 'nop (pJ)', 'dram (pJ)', 'comp (pJ)']
        for buf_name in self.buf_cost_dict.keys():
            header += [buf_name + ' (pJ)']
        header += ['energy (pJ)', 'btlnect']
        str_table = [header]
        for order in range(len(self.order_latency)):
            info = [order]
            energy_tot = 0
            latency = self.order_latency[order]
            noc_cost = self.order_noc_cost[order]
            nop_cost = self.order_nop_cost[order]
            dram_cost = self.order_dram_cost[order]
            comp_cost = self.order_comp_cost[order]
            info.append(latency)
            info.append(noc_cost)
            info.append(nop_cost)
            info.append(dram_cost)
            info.append(comp_cost)
            energy_tot += nop_cost + nop_cost + dram_cost + comp_cost
            for energy_list in self.buf_cost_dict.values():
                energy_tmp = energy_list[order]
                energy_tot += energy_tmp
                info.append(energy_tmp)
            info.append(energy_tot)
            if self.bottleneck[order] == 0:
                info.append('in')
            elif self.bottleneck[order] == 1:
                info.append('comp')
            elif self.bottleneck[order] == 2:
                info.append('out')
            else:
                raise ValueError(f'In execution order {order}, the bottleneck should be (nop move in)/(compute)/(nop '
                                 f'move out)')
            str_table.append(info)
        info = ['total']
        latency_tot = sum(self.order_latency)
        energy_tot = 0
        info.append(latency_tot)
        noc_cost = sum(self.order_noc_cost)
        nop_cost = sum(self.order_nop_cost)
        dram_cost = sum(self.order_dram_cost)
        comp_cost = sum(self.order_comp_cost)
        energy_tot += nop_cost + dram_cost + comp_cost
        info += [noc_cost, nop_cost, dram_cost, comp_cost]
        for energy_list in self.buf_cost_dict.values():
            energy_tot += sum(energy_list)
            info += [sum(energy_list)]
        info.append(energy_tot)
        info.append('-')
        str_table.append(info)
        str_ = tabulate(str_table, headers='firstrow', tablefmt='grid')
        return str_
